=== franciscobr0928/ordinario-ftw/xml/usuarios.dtd
<!ELEMENT usuarios (usuario+)>
<!ELEMENT usuario (matricula, contrasena, nombre)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT contrasena (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>

=== franciscobr0928/ordinario-ftw/xml/usuarios.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE usuarios SYSTEM "usuarios.dtd">
<usuarios>
    <usuario>
        <matricula>zs24013350</matricula>
        <contrasena>12345</contrasena>
        <nombre>Francisco Báez Rodríguez</nombre>
    </usuario>
    <usuario>
        <matricula>zs24013351</matricula>
        <contrasena>12345</contrasena>
        <nombre>José Rómulo Sosa Ortiz</nombre>
    </usuario>
    <usuario>
        <matricula>zs24013352</matricula>
        <contrasena>12345</contrasena>
        <nombre>Luis Miguel Gallego Basteri</nombre>
    </usuario>
</usuarios>
